### ISSUE TITLE
iOS Disagrees with detection

### ISSUE THREAD

**Issue by markarupert** [timbru31/cordova-plugin-detect-webview-engine#67]
I installed this plugin and it is telling me I am using WKWebview but when I upload the app the the App Store the geniuses at Apple claim it is UIWebView. Any ideas why that would be?

**Comment by timbru31** [comment]
Probably you have some plugins installed, that still use UIWebView (e.g., some sorts of overlays, inappbrowser etc.). This plugin just checks the "main" WebView that's used to render your `index.html` file. I'd recommend you open Xcode and search for the "UIWebView" references.

**Comment by timbru31** [comment]
I'm not 100% sure if Apple would reject a check such as `self.webView is UIWebView` for deprecation - I'll need to upload a dummy app to check.

**Comment by markarupert** [comment]
Thanks for the reply.

I am not sure since I did this at the same time, but I removed cordova-plugin-detect-webview-engine and then replaced inappbrowser with cordova-plugin-inappbrowser-wkwebview and I was able to upload without the warning.
